### ISSUE TITLE
toFile is not a function

### ISSUE THREAD

**Issue by abhiit61** [LoicMahieu/PDFKitJS#4]
Hi,

I have following code in my project. But this shows error "pdf.toFile is not a function"

var PDFKit = require('pdfkit');

```
    pdf = new PDFKit('html', html);

    pdf.toFile('google.pdf', function (err, file) {
      console.log('File ' + file + ' written');
    });
```

**Comment by LoicMahieu** [comment]
Sorry I am late. Your error is strange. Anyway I suggest you to not using the ugly module and switch to https://github.com/devongovett/node-wkhtmltopdf
