### ISSUE TITLE
Cannot find module 'pdfkitjs'

### ISSUE THREAD

**Issue by tzohpilotl** [LoicMahieu/PDFKitJS#5]
In the npm page, docs state that you should `require('pdfkitjs');`, that doesn't work but `require('pdfkit');` does, why  is that?

**Comment by LoicMahieu** [comment]
Hi @azaroma 
Indeed, you need to install `pdfkitjs` instead of `pdfkit`. I fixed the readme.

But I strongly recommend you to not use this package that is not longer maintained. [https://github.com/devongovett/node-wkhtmltopdf](devongovett/node-wkhtmltopdf) do the same job with a nicer API!
